### PR TITLE
no-default, no ctx

### PR DESCRIPTION
**Pull request by yoshuawuyts**
cc/ @lrlna - for merry too

### CODE REVIEW

**Review by lrlna — APPROVED** [review]
this means i can get `params` through just `params` right? 'cause the way merry gets it rn is a bit of a hack ahah

(otherwise code looks ace!)

**Comment by yoshuawuyts** [comment]
yep! - added you as an owner; merge & publish major? :D

**Comment by lrlna** [comment]
@yoshuawuyts can't publish to npm, can you double check on the perms?

**Comment by lrlna** [comment]
errrr sorry wasn't able to publish to npm for some reason (lol i know this was 28 days ago but i forgot), so there is a major now

**Comment by yoshuawuyts** [comment]
All good!

**Pull request merged**
